### ISSUE TITLE
Manipulating team members results in GitHubClientException with HTTP Code 422

### ISSUE THREAD

**Issue by torunar** [tan-tan-kanarek/github-php-client#103]
The issue probably occurs because the deprecated **members** API is used in
* `getTeamMember()`:
https://github.com/tan-tan-kanarek/github-php-client/blob/master/client/services/GitHubOrgsTeams.php#L90
* `addTeamMember()`:
https://github.com/tan-tan-kanarek/github-php-client/blob/master/client/services/GitHubOrgsTeams.php#L98
*  `removeTeamMember()`:
https://github.com/tan-tan-kanarek/github-php-client/blob/master/client/services/GitHubOrgsTeams.php#L117

Accordingly to https://developer.github.com/v3/orgs/teams/,
`/memberships/` should be used instead of `/members/` and response codes are different.

**Comment by tan-tan-kanarek** [comment]
Thank you for your comment.
Would you be able to change it, test it and pull request it?

**Comment by torunar** [comment]
@tan-tan-kanarek, sure: https://github.com/tan-tan-kanarek/github-php-client/pull/104
