### ISSUE TITLE
Removing the organization member with responseIfRequesterIsNotAnOrganizationMember()

### ISSUE THREAD

**Issue by torunar** [tan-tan-kanarek/github-php-client#105]
https://github.com/tan-tan-kanarek/github-php-client/blob/master/client.md#methods-31

The name of the method is quite misleading as it actually **removes** the member from the organization.
So what's the real purpose of it?

**Comment by tan-tan-kanarek** [comment]
You're right, it's auto-generated code that generated from non-standard documentation, it should be called remove member.
Fixed here: https://github.com/tan-tan-kanarek/github-php-client/pull/106
