### ISSUE TITLE
listIssues skips some results

### ISSUE THREAD

**Issue by cristiano-federico** [tan-tan-kanarek/github-php-client#127]
`
$issues = $client->issues->listIssues($owner, $repo, $state="closed")`;
`foreach($issues as $issue) {
     print_r($issue->getTitle());
}`

This listIssues method is literally skipping some results in the response, may it be a problem with private repositories? I checked the OAuth token but it allows me to have total control of my repo, so I can't really figure this out.

**Comment by tan-tan-kanarek** [comment]
If the response doesn't contain them then I guess that the problem is not in the client lib.

**Comment by cristiano-federico** [comment]
Problem was paginated result capped at 30, but how can I call this method using per_page or page parameters in order to get all my issues?

**Comment by tan-tan-kanarek** [comment]
You can use $client->getNextPage() to get the next page.
