### ISSUE TITLE
Error 400 Bad Request when updating a release

### ISSUE THREAD

**Issue by piRGoif** [tan-tan-kanarek/github-php-client#128]
Hello,

Thanks for this great api !

I was trying to update a release in one of my repo : 
`		$client->repos->releases->update(REPO_ORG, REPO_NAME, $sReleaseId, $sTag, null, $sTag, $sReleaseDesc);`
The code was failing with a 400 Bad Request : in the response body, the error message was : "Problems parsing JSON".

Looking at the code, I saw that when using the PATCH HTTP method, the $data array was sent as it to curl (GitHubClientBase.php:305).
With the PUT method the $data is encoded with a json_encode call.
In the release update method also, there isalready a json_encode call, but it is commented (services/GitHubReposReleases.php:109). Uncommenting it solved my problem.

**Comment by tan-tan-kanarek** [comment]
Thanks for your comment,  a pull request will be appreciated

**Comment by piRGoif** [comment]
Hello, I've just done it :)

**Comment by piRGoif** [comment]
As the PR was merged (thanks !), I assume this issue can now be closed ?

**Comment by tan-tan-kanarek** [comment]
Thank you for the PR and issue.
