### ISSUE TITLE
How to use this method? listReposReleases

### ISSUE THREAD

**Issue by runtman** [tan-tan-kanarek/github-php-client#130]
I don't see this listed in the client.md at all `listReposReleases` curious as this is a public method how can it be accessed?

I have tried:

`$client->repos->listReposReleases($username, $repo);`

I have also tried the listed methods:

`$client->repos->reposDownloads->listDownloadsForRepository($username, $repo);` 

I essentially just want alist of my releases and their assets.

P.s thank you for the repo :)

Edit: `$releases = $client->repos->releases->listReposReleases($username, $repo);`

I believe this is what I need, but it appears to bring back an empty array.

**Comment by runtman** [comment]
This can be closed, turned out my releases were pushed as tags and this isn't allowed.

**Comment by tan-tan-kanarek** [comment]
Cool, thanks.

**Comment by runtman** [comment]
I am trying to get tags instead, but these are all protected. I see it's a public function, is this protected at an API level?

`[name:protected] => v0.2`

```
[:error] [pid 4939] [client ::1:43194] PHP Fatal error:  Uncaught Error: Cannot access protected property GitHubTag::$name```
