### ISSUE TITLE
Bug with Function: editAnIssue

### ISSUE THREAD

**Issue by ff1601com** [tan-tan-kanarek/github-php-client#134]
Hey there,

I run into a problem when I tried updating the state of an issue.

Whenever I tried to update my issue, I got the following error code:
```
In GitHubClientBase.php line 436:
                                                                                 
Expected status [200], actual status [422], URL [/repos/testOwner/testRepo/issues/87] 
```

So naturally I turned on the debug-log and got the following message:

```
{"message":"Invalid request.\n\nFor 'links/1/schema', \"{\\\"state\\\":\\\"closed\\\"}\" is not an object or null.","documentation_url":"https://developer.github.com/v3/issues/#edit-an-issue"}
```

Looks like the json-object got kinda destroyed.

I then tried to remove the following line in your editAnIssue-Function and got it working:
```php
$data = json_encode($data);
```

Anyway, if I print out $data after the json encode, it looks just fine.
```
{"state":"closed"}
```

It almost seems like it gets json_encoded multiple times?

##

Do you have an idea how this issue arises or how to fix it without removing the `$data = json_encode($data);` - line?

**Comment by ff1601com** [comment]
So I just found out it gets json_encoded another time in GitHubClientBase.php on line: 306

```php
$content = json_encode($data, JSON_FORCE_OBJECT);
```

My guess is, that the json_encode in the `editAnIssue` function is causing the problem.

**Comment by ff1601com** [comment]
I may be wrong, not sure though. 
In case I am right i created a pull-request.

If I'm wrong and the problem is elswhere or on my side (tried it with multiple different Requests), then just close this issue and decline the pr.

**Comment by ff1601com** [comment]
One example Request that leads to the error is the following:

```php
$client->issues->editAnIssue('myOwner', 'myRepo', null, myNumber, null, null, 'closed', null, null);
```

**Comment by tan-tan-kanarek** [comment]
Thank a lot, solved here: https://github.com/tan-tan-kanarek/github-php-client/pull/135
