### ISSUE TITLE
how to call labels for an issue

### ISSUE THREAD

**Issue by deepaknverma** [tan-tan-kanarek/github-php-client#20]
how can I call label for a particular issue

**Comment by flashadvocate** [comment]
@deepaknverma might be missing it, but is there a direct way to pull issues marked with a specific label, as opposed to looping through all of the labels belonging to an issue to decide if it's one I want?

**Comment by tan-tan-kanarek** [comment]
GitHubPulls::listPullRequests should do the trick, see also the official documentation: https://developer.github.com/v3/pulls/#list-pull-requests

**Comment by flashadvocate** [comment]
Ah thanks tan-tan. I see it mentions "all pull requests are issues but not
vice versa". I'm not necessarily interested in just PRs but all issues
marked with a specific label (question or bug, for example)

**Comment by tan-tan-kanarek** [comment]
See fix: https://github.com/tan-tan-kanarek/github-php-client/pull/53

**Comment by flashadvocate** [comment]
Awesome @tan-tan-kanarek thanks for the great work! :)
