### ISSUE TITLE
Help with github-php-client

### ISSUE THREAD

**Issue by averony** [tan-tan-kanarek/github-php-client#42]
Hello. Sorry about my english. I'd find your github-php-client . I think that it i realy need for my https://github.com/averony/datebott . Please correct me if I'm wrong. Your code allows you to log your experiments at github, and make changes in files of your repository by means of curl? Now I have the task to automate the process of adding new rows in the file https://github.com/averony/datebott/blob/master/woman.js . woman.js - is a database in text form. When you try to use your code I get the following error:
https://github.com/averony/datebott/blob/master/supertest.js

**Comment by tan-tan-kanarek** [comment]
My guess would be that you're using the wrong password.
See in the response: "message":"Bad credentials".

**Comment by averony** [comment]
omg) Very thank you! Sorry for this)
