### ISSUE TITLE
Commit changes with your code

### ISSUE THREAD

**Issue by averony** [tan-tan-kanarek/github-php-client#43]
Sorry, it's me again. Thank you again for the help last time. I finally made it. But the thing is that that is not what I need. Maybe you have a solution for my problem. I need to make changes(Commit changes) to the file base https://github.com/averony/datebott/edit/master/woman.js . Let's say I have a server receives payment, your code works and through curl automatically changes the content in this file. You can implement something similar with your help? Or can you tell me any other solution?
Thanks in advance, you help me a lot.

**Comment by tan-tan-kanarek** [comment]
Sorry,
I don't understand your need.
Anyway, the github API doesn't support committing or pushing commits to the repo.

**Comment by averony** [comment]
Ty, realy i need committing or pushing commits to the repo. I know people can do this.

**Comment by tan-tan-kanarek** [comment]
You can use cli scripts or call cli from php, but not using this API library or any github API library.

**Comment by averony** [comment]
Ty
