### ISSUE TITLE
404 on issues that don't exist

### ISSUE THREAD

**Issue by flashadvocate** [tan-tan-kanarek/github-php-client#54]
When an issue cannot be found, there's currently no recourse other than a mismatched response. (404 instead of 200).

**Comment by tan-tan-kanarek** [comment]
Please send your code so I'll understand what you're trying to accomplish, mostly in terms of what you expected to happen and what actually happened.

**Comment by flashadvocate** [comment]
https://github.com/flashadvocate/Division-Tracker/blob/master/vendor/github/GitHubClientBase.php#L384

When querying for an issue that doesn't exist, an exception is thrown,
rather than returning the response. I'd like to be able to handle a 404
with an error of my own.

**Comment by flashadvocate** [comment]
https://github.com/tan-tan-kanarek/github-php-client/blob/master/client/GitHubClientBase.php#l384

When querying for an issue that doesn't exist:

ex
 ```php
$git->issues->getIssue(self::$owner, self::$repo, $id);
```

where id is an issue id that is erroneous, usually because it was typed in, an exception is thrown, rather than returning the response. It would be nice to be able to handle this error, rather than forcing an exception.

**Comment by tan-tan-kanarek** [comment]
It's easy, just catch the exception.

```php
try{
  $issue = $git->issues->getIssue(self::$owner, self::$repo, $erroneousId);
} catch(GitHubClientException $e){
  $errorDescription = $e->getMessage();
}
```

I decided to throw exception according to the returned HTTP error codes, assuming that if github team decided it should be considered as error than I should too.

Another approach would be to list all issues (listAllIssues) using some filter and check the number of returned results.

T.

**Comment by flashadvocate** [comment]
Fair enough. Thanks :)
