### ISSUE TITLE
problem in pull_request create new review comment

### ISSUE THREAD

**Issue by shreyans264** [tan-tan-kanarek/github-php-client#55]
the function name is createComment but it actually deletes the comment (looks like it),
have fixed this problem here: https://github.com/shreyans264/github-php-client
(checkout client/services/GitHubPullsComments.php for same)

plz reply..

**Comment by tan-tan-kanarek** [comment]
Could you please open a pull-request?

**Comment by shreyans264** [comment]
Pull request opened

**Comment by tan-tan-kanarek** [comment]
Merged, thank you.
