### ISSUE TITLE
Problem while sending POST Request(like sending a Review Comment) in a private repository

### ISSUE THREAD

**Issue by shreyans264** [tan-tan-kanarek/github-php-client#61]
Error: Uncaught exception 'GitHubClientException' with message 'Expected status [201], actual status [422]

**Comment by tan-tan-kanarek** [comment]
I'll need more information in order to help you, what service and action exactly did you use?

**Comment by tan-tan-kanarek** [comment]
@shreyans264, can I close this issue?
