### ISSUE TITLE
Incomplete GitHubCommitCommitAuthor?

### ISSUE THREAD

**Issue by djplaner** [tan-tan-kanarek/github-php-client#65]
G'day 

First, thanks for the client.  Found it very useful for a project.

It appears that GitHubCommitCommitAuthor is incomplete. It doesn't actually declare the class variables/methods required to actually use it.

No great show stopper.  I've been able to make the changes myself. 

Wondering if I've missed some important point?

David.

**Comment by tan-tan-kanarek** [comment]
Some of the code was generated by parsing the documentation and as such some of it was generated wrong.
Please open a pull-request with your changes.

**Comment by djplaner** [comment]
Done - I believe.

**Comment by tan-tan-kanarek** [comment]
Thank you.
