### ISSUE TITLE
OAuth Authenication

### ISSUE THREAD

**Issue by iAmWillX** [tan-tan-kanarek/github-php-client#68]
Hello There! Thank you for creating this awesome API.

Unfortunately, I have some issues with it. I am currently attempting to connect with OAuth however I keep receiving 404 responses. Do you perhaps have some code examples or guides on how to set this up?

Thank you,
Bart

**Comment by tan-tan-kanarek** [comment]
Hi, thank you for your words, I'm glad you find it useful.

The client library written without OAuth support as a login method.
However you can use it with basic credentials to manage your OAuth tokens.

T.

**Comment by bart7567** [comment]
Alright Thanks.
