### ISSUE TITLE
What License is this under?

### ISSUE THREAD

**Issue by smcjones** [tan-tan-kanarek/github-php-client#70]
This is a great project, makes it very easy to get going with GitHub. However, I don't see a LICENSE so I'm wondering, what is this license under? Is it GPL compatible?

Thanks,

Sean

**Comment by smcjones** [comment]
After posting I noticed in the Composer file that it is proprietary. Is this accurate? Thanks.

**Comment by djplaner** [comment]
Ahh, hadn't noticed that. A proprietary license means I can't use it for the project I'm thinking of. Oh well.

**Comment by tan-tan-kanarek** [comment]
I wrote this code for people to use it and I'll be glad that you'll use it in any way, and if you'll get reach by using it even better, feel free to use it.
I don't know what license should I associate with it in order to enable it but I'm open to recommendations.

**Comment by smcjones** [comment]
There are a lot of Open Source licenses to choose from, and I'm not a lawyer so what I say is based on my own research and not 100% truth. 

Many people will need an Open Source license if they're developing Open Source software themselves. If you're looking for suggestions, I can name four popular ones: GPL v 3 (very permissive, requires all derivative works to be GPL compatible), Apache v 2 (similar with added patent protection), Creative Commons v4 (GPLv3 compatible), or MIT (allows use in proprietary software as well). MIT is the most permissive and just requires inclusion of the original copyright notice. Given your statement that you just wrote it for people to use it, MIT might be the best way forward for you as it allows people to use it with the most flexibility. I could be wrong. Any lawyers willing to chime in, please do.

**Comment by djplaner** [comment]
Also no lawyer, but +1 MIT.  But any of the others mentioned would work in my situation.

**Comment by tan-tan-kanarek** [comment]
License added: https://github.com/tan-tan-kanarek/github-php-client/pull/78
