### ISSUE TITLE
webApplicationFlow - missing?

### ISSUE THREAD

**Issue by djplaner** [tan-tan-kanarek/github-php-client#71]
The API docs list "webApplicationFlow" as a method for GitHubOauth.  Can't find it in the code and attempts to use it (not suprisingly) get

Fatal error:  Call to undefined method GitHubOauth::webApplicationFlow()

**Comment by tan-tan-kanarek** [comment]
This library is moving forward with Github APIs in the same pace that we update it as a community.
I'll be glad to have this method implemented, so if you need it, just implement it and we all will be grateful.
