### ISSUE TITLE
Needs a stable release

### ISSUE THREAD

**Issue by acuthbert** [tan-tan-kanarek/github-php-client#77]
Hi - the library is great - thanks!

But could you create an official version tag and publish that to packagist? I'm trying to use the library in a project but don't want to set the minimum stability to dev if I can avoid it!

Thanks!

**Comment by tan-tan-kanarek** [comment]
Release 1.0.0: https://github.com/tan-tan-kanarek/github-php-client/releases/tag/1.0.0
