### ISSUE TITLE
Can't create issues with labels

### ISSUE THREAD

**Issue by KareemMAX** [tan-tan-kanarek/github-php-client#86]
How can I create an issue with label

I tried this code but it didn't work
```php
$client->issues->createAnIssue('KareemMAX', 'Minecraft-Skiner', $_POST["title"], $_POST["body"],null,null,null,array("Bug tracker"));
```

**Comment by tan-tan-kanarek** [comment]
Seems like you place eight variables instead of seven, please remove one null.

**Comment by KareemMAX** [comment]
It works now, Sorry for the inconvenience.
