### ISSUE TITLE
How to iterate over all pages

### ISSUE THREAD

**Issue by ryandesign** [tan-tan-kanarek/github-php-client#89]
It's unclear how to iterate over all pages of results. I can get the first page, the next page, or the last page, but I don't see how to construct a loop that iterates over every page from the first to the last. Your existing sample code assumes there are exactly two pages of results. Your full API reference does not include the pagination functions.

**Comment by DeepDiver1975** [comment]
Yes - this requires some more documentation please

**Comment by tan-tan-kanarek** [comment]
See: https://github.com/tan-tan-kanarek/github-php-client#pagination
