### ISSUE TITLE
How to list milestones

### ISSUE THREAD

**Issue by ryandesign** [tan-tan-kanarek/github-php-client#92]
I'm confused about how to get a list of milestones in a repository.

In GitHubIssuesLabels.php you have `listAllLabelsForThisRepository()` which lists the labels, and `getSingleLabel()` which gets a single label. This makes sense.

But in GitHubIssuesMilestones.php you have `listMilestonesForRepository()` which does not list milestones but rather gets a single milestone.

**Comment by tan-tan-kanarek** [comment]
Fixed in https://github.com/tan-tan-kanarek/github-php-client/pull/93.
