### ISSUE TITLE
Trying to use paged results as per readme example, but getPage() doesn't exist

### ISSUE THREAD

**Issue by rivimey** [tan-tan-kanarek/github-php-client#94]
getPage isn't there and I don't see how to detect you've seen (or are on) the last available page.

**Comment by tan-tan-kanarek** [comment]
getPage added only lately: https://github.com/tan-tan-kanarek/github-php-client/commit/62efd523b97975120ea7977f48430b1d49ad572c

Make sure you have the latest code.
