### ISSUE TITLE
 Fatal error:  'GitHubRepoContentCommit' not found

### ISSUE THREAD

**Issue by stephenharris** [tan-tan-kanarek/github-php-client#97]
This class is specified as return for some `GitHubRepoContents` methods. e.g.: https://github.com/tan-tan-kanarek/github-php-client/blob/dd0d8b4757a320481630732605308ced83eb0467/client/services/GitHubReposContents.php#L59

But I can't find any trace of that class anywhere except for this issue: #96 

Here's the stack trace:

Stack trace:
> .../vendor/tan-tan-kanarek/github-php-client/client/GitHubClientBase.php(355): GitHubClientBase->parseResponse('...', Object(stdClass), 'GitHubRepoConte...', 201, false)
.../vendor/tan-tan-kanarek/github-php-client/client/services/GitHubReposContents.php(59): GitHubClientBase->request('...', 'PUT', Array, 201, 'GitHubRepoConte...')
 ...index.php(15): GitHubReposContents->createFile('username', 'repo', 'file.txt', 'message', '...encoded content...')
 {main}
  thrown in ...vendor/tan-tan-kanarek/github-php-client/client/GitHubClientBase.php on line 437

Does this class need to be defined, or is the return type wrong?

**Comment by stephenharris** [comment]
Replacing `GitHubRepoContentCommit` with `GitHubRepoCommit` in https://github.com/tan-tan-kanarek/github-php-client/blob/518de57d7c99bb4ae503b3897a3b76fc231ae0b5/client/services/GitHubReposContents.php seems to work

**Comment by tan-tan-kanarek** [comment]
Resolved in https://github.com/tan-tan-kanarek/github-php-client/pull/98
